Pid controller
moevm/mse1h2024-drones pull request #11
Opened 2024-03-03 21:20 UTC by Cottoffey

Запуск тестов:

python ./src/PidTests.py

2024-03-05 09:48 UTC, danilasimanok requested changes
Добавь, пожалуйста, gitignore, который не будет подхватывать папку `__pycache__`. Она в репозитории не нужна.

2024-03-07 10:26 UTC, danilasimanok commented on src/PIDController.py
> +            move[i] = self.prevErr[i] + self.kI * currErr[i] + self.kP * (currErr[i] - self.prevErr[i]) + self.kD * (currErr[i] - 2 * self.prevErr[i] + self.prevPrevErr[i])
Формула выглядит неправильно. Почему интегральный коэффициент стоит перед текущей ошибкой, а не перед ее интегралом? И почему в дифференциальной части ты берешь вторую производную? Почему ошибку умножаешь на интегральный коэффициент?

Переделай, пожалуйста, так чтобы

- `PIDController` работал от одной "координаты"; пусть будет только `x`, у такого и реализация проще, и мы потом сможем его легко обобщить до текущего;
- формула вычисления зависела от времени;
- она явно имела вид `kP * e(t) + kD * de(t)/dt + kI * Ie(t)`;
- она использовала только предыдущий шаг: возьми формулы численного интегрирования/дифференцирования попроще; переделаем, если будут недостаточно точными.

2024-03-07 16:37 UTC, Cottoffey commented
Формулы численного интегрирования самая простая и в ней нужна вторая производная.
[Формула](https://en.wikipedia.org/wiki/Proportional%E2%80%93integral%E2%80%93derivative_controller#Discrete_implementation)

2024-03-07 16:38 UTC, Cottoffey commented
И в формуле действительно была ошибка, но не с коэффициентами.

2024-03-08 17:40 UTC, danilasimanok requested changes
Помимо описанных ранее комментариев, также приведи, пожалуйста, написанный тобой код к стандарту [PEP 8](https://peps.python.org/pep-0008/).

2024-03-08 17:40 UTC, danilasimanok commented on src/__pycache__/PIDController.cpython-310.pyc
Этого файла и папки, которая его содержит, быть не должно. Удали их, пожалуйста, из репозитория.

2024-03-08 17:40 UTC, danilasimanok commented on src/PidTests.py
> +        self.assertEqual(move, -2.800999999999999)
Думаю, что тут и в прочих местах при сравнении чисел с плавающей точкой вместо `assertEqual` лучше использовать `assertTrue(math.isclose(...))`.

2024-03-08 17:40 UTC, danilasimanok commented on src/PidTests.py
Либо оба `PID`, либо оба `Pid`.

2024-03-08 17:40 UTC, danilasimanok commented on src/PidTests.py
И еще, с нулевым временем придумай чего-нибудь осмысленное. Это-то очевидный corner-case.

2024-03-08 17:40 UTC, danilasimanok commented on src/PidTests.py
> +        move = pctr.Calculate(x0, x, 1)
Почему не заинлайнить эти переменные? Никакого смысла логически их отделять от создания `move` нет. Относится ко всем подобным случаям.

2024-03-08 17:40 UTC, danilasimanok commented on src/PIDController.py
> +import matplotlib.pyplot as plt
Эти библиотеки не являются частью установки `python` по умолчанию. Создай, пожалуйста, файл `requirements.txt` и опиши в нем все сторонние библиотеки, необходимые для запуска.

2024-03-08 17:40 UTC, danilasimanok commented on src/PIDController.py
> +        move = self.prevMove + self.kI * currErr * dt + self.kP * (currErr - self.prevErr) + self.kD * (currErr - 2 * self.prevErr + self.prevPrevErr) / dt
Очень длинная строчка. Трудно читать. Предлагаю вместо `prevMove` сохранять `move`, а здесь писать

```python
move +=
    kI * ...
    + kP * ...
    + kD * ...
```

2024-03-08 17:40 UTC, danilasimanok commented on src/PidTests.py
> +import PIDController as pid
Из этого модуля ты используешь только `PIDController`. Почему не

```python
from PIDController import PIDController
```

?

2024-03-23 16:19 UTC, danilasimanok requested changes
Имена файлов поменяй, очень пожалуйста. https://peps.python.org/pep-0008/#package-and-module-names

И папку верхнего уровня переименуй в `/pid_controller`. Мы еще будем реорганизовывать структуру папок, так что это потом, вероятно, поменяется, но пока поменяй, пожалуйста.

2024-03-25 16:06 UTC, danilasimanok requested changes
Нет, так не пойдет. Одна ветка — одна фича. Сначала надо было закончить pid controller, а потом впиливать его в дрона, это во-первых.
Во-вторых, ты никак не изменил процедуру запуска из wiki. У меня при попытке ее проделать на твоей ветке пишется

```
[webots_controller_Mavic_2_PRO-2] ModuleNotFoundError: No module named 'aurco_follower.pid_controller'
```

Откати, пожалуйста, ветку до слияния с `feat/minimal-example`. Ее будем сливать с мастером, а интеграцию контроллера и драйвера надо делать в отдельной ветке.

В новой ветке не забудь, пожалуйста, про инструкцию по запуску. Измени ее, если необходимо.

2024-03-27 16:08 UTC, danilasimanok approved these changes

2024-03-27 16:09 UTC, merged