Aruco_detect
moevm/mse1h2024-drones pull request #16
Opened 2024-03-21 17:17 UTC by NguyenHai-LETI

Aruco_detect done testCase in process

2024-03-28 17:51 UTC, danilasimanok requested changes
Помимо указанного в комментариях, также нужно убрать все содержимое `results`. Если я правильно понял написанный код, то оно должно генерироваться самой программой. В нынешнем виде непонятно, что проверяет `test_saveResult.py`, поскольку даже если программа вообще не сработала, они все равно покажут, что все хорошо.

2024-03-28 17:51 UTC, danilasimanok commented on ARuco_Detect/__pycache__/detect_img.cpython-310.pyc
Этого файла быть не должно. И в целом `__pycache__` в репозиторий отправлять не нужно.

2024-03-28 17:51 UTC, danilasimanok commented on ARuco_Detect/instruction.md
> +    + OpenCV
Эту зависимость вполне можно было бы вынести в `requirements.txt`

2024-03-28 17:51 UTC, danilasimanok commented on ARuco_Detect/test/test_detectMarkers.py
> +import numpy as np
Эта зависимость не была указана в инструкции. Укажи ее, пожалуйста, в `requirements.txt`.

2024-03-28 17:51 UTC, danilasimanok commented on ARuco_Detect/test/test_detectMarker.jpg
Этот файл в репозитории не нужен. Удали его, пожалуйста.

2024-03-28 17:51 UTC, danilasimanok commented on ARuco_Detect/test/test_saveResults.jpg
Этот файл в репозитории не нужен. Удали его, пожалуйста.

2024-04-01 15:52 UTC, NguyenHai-LETI commented on ARuco_Detect/__pycache__/detect_img.cpython-310.pyc
удалил

2024-04-01 15:52 UTC, NguyenHai-LETI commented on ARuco_Detect/instruction.md
> +    + OpenCV
удалил и добавил в requirements.txt

2024-04-01 15:55 UTC, NguyenHai-LETI commented on ARuco_Detect/test/test_detectMarker.jpg
удалил

2024-04-01 15:55 UTC, NguyenHai-LETI commented on ARuco_Detect/test/test_saveResults.jpg
удалил

2024-04-01 16:12 UTC, NguyenHai-LETI commented on ARuco_Detect/test/test_detectMarkers.py
> +import numpy as np
добавил в requirements.txt

2024-04-05 19:27 UTC, danilasimanok requested changes

2024-04-05 19:27 UTC, danilasimanok commented on ARuco_Detect/requirement.txt
> +opencv-python==4.5.4
Попытался установить зависимости командой `pip install -r requirements.txt` и получил следующий ответ

```
ERROR: Could not find a version that satisfies the requirement opencv-python==4.5.4 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72, 4.8.0.74, 4.8.0.76, 4.8.1.78, 4.9.0.80)

ERROR: No matching distribution found for opencv-python==4.5.4
```

2024-04-11 16:03 UTC, NguyenHai-LETI commented on ARuco_Detect/requirement.txt
> +opencv-python==4.5.4
исправил содержимое файла requirements.txt

2024-04-21 20:53 UTC, Cottoffey commented
Исправил пару ошибок. 
Изображение получается и отправляется в нужный топик. 
Но почему он ни разу не определил положение маркера, хотя на картинке его четко видно.

2024-05-20 08:51 UTC, NguyenHai-LETI commented
- Маркер определен и отображается нормально на GUI, данные изображения для определения берутся из /Mavic_2_PRO/camera/image_color
- Координаты смещения по оси x отправляется в /marker

2024-05-21 18:49 UTC, danilasimanok approved these changes

2024-05-21 18:49 UTC, merged